/*
Rotten Tomatoes

Test our API services using I/O Docs.

The version of the OpenAPI document: 1.0
Contact: mike.ralphson@gmail.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  DvdListsApi,
  DetailedInfoApi,
  MovieListsApi,
  SearchApi,
  TopLevelListsApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { RottenTomatoesCustom } from "./client-custom";

export class RottenTomatoes extends RottenTomatoesCustom {
  readonly dvdLists: DvdListsApi;
  readonly detailedInfo: DetailedInfoApi;
  readonly movieLists: MovieListsApi;
  readonly search: SearchApi;
  readonly topLevelLists: TopLevelListsApi;

  constructor(configurationParameters: ConfigurationParameters) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.dvdLists = new DvdListsApi(configuration);
    this.detailedInfo = new DetailedInfoApi(configuration);
    this.movieLists = new MovieListsApi(configuration);
    this.search = new SearchApi(configuration);
    this.topLevelLists = new TopLevelListsApi(configuration);
  }

}
